---
- name: iptables systemd
  systemd:
    name: iptables
    enabled: yes
    state: restarted
    
- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  listen: persist iptables
