---
- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd
- name: Replace nginx.conf
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - nginx systemd
